// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AuthPromptEventPayload is broadcast (helper → GUI) when an OpenVPN tunnel is
 * waiting for the user to enter credentials.
 * 
 * ChallengeKind is empty for a plain username/password prompt, "static"
 * (SCRV1 — collect a challenge response alongside the password, in the same
 * prompt) or "dynamic" (CRV1 — collect a response in a SEPARATE prompt,
 * after the base password already succeeded; the GUI should show a
 * response-only form with no username/password fields in this case). The
 * server-issued opaque state ID for a dynamic challenge is an internal
 * wire-protocol detail the frontend never needs and is not included here.
 */
export class AuthPromptEventPayload {
    /**
     * Creates a new AuthPromptEventPayload instance.
     * @param {Partial<AuthPromptEventPayload>} [$$source = {}] - The source object to create the AuthPromptEventPayload.
     */
    constructor($$source = {}) {
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["challenge_kind"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["challenge_text"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["challenge_echo"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["challenge_concat"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthPromptEventPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthPromptEventPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthPromptEventPayload(/** @type {Partial<AuthPromptEventPayload>} */($$parsedSource));
    }
}

/**
 * LogEntry is a single structured log record forwarded from the helper
 * to the GUI (and from the GUI to the frontend LogViewer). We keep it flat
 * — no nested attrs — because the viewer just renders a one-line per entry.
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * RFC3339
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * "debug" | "info" | "warn" | "error"
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "helper" | "gui"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * human-readable text (already includes attrs)
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}
