// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 */
export const ConnectionStatus = domain$0.ConnectionStatus;

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 * @typedef {domain$0.ConnectionStatus} ConnectionStatus
 */

/**
 * DNSLeakResult mirrors diag.DNSLeakResult for Wails JSON serialisation.
 */
export class DNSLeakResult {
    /**
     * Creates a new DNSLeakResult instance.
     * @param {Partial<DNSLeakResult>} [$$source = {}] - The source object to create the DNSLeakResult.
     */
    constructor($$source = {}) {
        if (!("leaked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["leaked"] = false;
        }
        if (!("dns_servers" in $$source)) {
            /**
             * @member
             * @type {DNSServer[]}
             */
            this["dns_servers"] = [];
        }
        if (!("test_domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["test_domain"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSLeakResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSLeakResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns_servers" in $$parsedSource) {
            $$parsedSource["dns_servers"] = $$createField1_0($$parsedSource["dns_servers"]);
        }
        return new DNSLeakResult(/** @type {Partial<DNSLeakResult>} */($$parsedSource));
    }
}

/**
 * DNSServer mirrors diag.DNSServer.
 */
export class DNSServer {
    /**
     * Creates a new DNSServer instance.
     * @param {Partial<DNSServer>} [$$source = {}] - The source object to create the DNSServer.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("is_vpn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_vpn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSServer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSServer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSServer(/** @type {Partial<DNSServer>} */($$parsedSource));
    }
}

/**
 * FoundConfig is a WireGuard .conf found on the filesystem.
 */
export class FoundConfig {
    /**
     * Creates a new FoundConfig instance.
     * @param {Partial<FoundConfig>} [$$source = {}] - The source object to create the FoundConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FoundConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FoundConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FoundConfig(/** @type {Partial<FoundConfig>} */($$parsedSource));
    }
}

/**
 * RouteEntry mirrors diag.RouteEntry for Wails JSON serialisation.
 */
export class RouteEntry {
    /**
     * Creates a new RouteEntry instance.
     * @param {Partial<RouteEntry>} [$$source = {}] - The source object to create the RouteEntry.
     */
    constructor($$source = {}) {
        if (!("destination" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destination"] = "";
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("flags" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flags"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RouteEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RouteEntry(/** @type {Partial<RouteEntry>} */($$parsedSource));
    }
}

/**
 * SavedCredentials holds the stored username + base password for an OpenVPN
 * tunnel. Returned by GetSavedCredentials so the auth modal can pre-fill fields.
 */
export class SavedCredentials {
    /**
     * Creates a new SavedCredentials instance.
     * @param {Partial<SavedCredentials>} [$$source = {}] - The source object to create the SavedCredentials.
     */
    constructor($$source = {}) {
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("base_password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedCredentials instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedCredentials}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedCredentials(/** @type {Partial<SavedCredentials>} */($$parsedSource));
    }
}

/**
 * TunnelInfo is the summary shown in the tunnel list.
 */
export class TunnelInfo {
    /**
     * Creates a new TunnelInfo instance.
     * @param {Partial<TunnelInfo>} [$$source = {}] - The source object to create the TunnelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("is_connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_connected"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {domain$0.Protocol}
             */
            this["protocol"] = domain$0.Protocol.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInfo(/** @type {Partial<TunnelInfo>} */($$parsedSource));
    }
}

/**
 * ZipImportResult holds the outcome of importing one .conf entry from a zip.
 */
export class ZipImportResult {
    /**
     * Creates a new ZipImportResult instance.
     * @param {Partial<ZipImportResult>} [$$source = {}] - The source object to create the ZipImportResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ZipImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ZipImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ZipImportResult(/** @type {Partial<ZipImportResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DNSServer.createFrom;
const $$createType1 = $Create.Array($$createType0);
