// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService is the Wails-bound service.
 * Storage (tunnel files, settings) stays in the GUI process.
 * Tunnel operations go through the helper via an ipc.ClientHolder (so the
 * helper can be re-spawned and the connection swapped without rebuilding
 * the whole service graph).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "../history/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tunnel$0 from "../tunnel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveTunnelNames returns every currently active tunnel name (WireGuard
 * AND OpenVPN — the helper supports multiple concurrent tunnels). Exported
 * for callers outside this package that need to act on the full active set
 * rather than the single "primary" name MethodActiveName reports (e.g. the
 * Wi-Fi auto-connect lifecycle's "disconnect everything" path).
 * @returns {$CancellablePromise<string[]>}
 */
export function ActiveTunnelNames() {
    return $Call.ByID(3482408702).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BaseName extracts the filename without extension from a path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function BaseName(path) {
    return $Call.ByID(3888008056, path);
}

/**
 * CheckConflicts loads a tunnel's config and scans local network interfaces
 * for routing overlaps (e.g. Tailscale, another WireGuard instance). Runs
 * entirely in the GUI process — no IPC needed. The frontend calls this before
 * Connect so it can show a warning dialog if conflicts exist.
 * @param {string} name
 * @returns {$CancellablePromise<tunnel$0.ConflictInfo[]>}
 */
export function CheckConflicts(name) {
    return $Call.ByID(604900757, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CheckForUpdate queries GitHub for a newer release.
 * @returns {$CancellablePromise<update$0.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(4127090372).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ClearConnectionHistory wipes the history file.
 * @returns {$CancellablePromise<void>}
 */
export function ClearConnectionHistory() {
    return $Call.ByID(3616246409);
}

/**
 * CloseHistorySessions closes any open history sessions with reason. Called
 * from gui.Run during shutdown so the UI doesn't show phantom "Active" rows
 * after a quit.
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function CloseHistorySessions(reason) {
    return $Call.ByID(3018497415, reason);
}

/**
 * CompleteOnboarding marks onboarding as done in settings.
 * @returns {$CancellablePromise<void>}
 */
export function CompleteOnboarding() {
    return $Call.ByID(655688232);
}

/**
 * Connect loads a tunnel config from local storage and asks the helper to
 * bring it up. The helper re-validates server-side. OpenVPN tunnels are routed
 * to the OpenVPN connect path.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Connect(name) {
    return $Call.ByID(3475995036, name);
}

/**
 * DeleteTunnel removes a tunnel from local storage. Rejects deletion of the
 * currently connected tunnel (would orphan the interface).
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTunnel(name) {
    return $Call.ByID(2920758891, name);
}

/**
 * Disconnect tears down whatever tunnel the helper currently has active.
 * If the call fails with a "client closed" error (the health monitor may have
 * swapped the client during a recovery), retry once with the fresh client.
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(3215959632);
}

/**
 * DisconnectTunnel disconnects a specific tunnel by name.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectTunnel(name) {
    return $Call.ByID(4027842506, name);
}

/**
 * ExportConfig returns the serialized text for display in the export dialog.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig(name) {
    return $Call.ByID(3219660626, name);
}

/**
 * ExportTunnel shows a native save dialog and writes the .conf file.
 * Returns the saved path, or empty string if the user cancelled.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportTunnel(name) {
    return $Call.ByID(2791885822, name);
}

/**
 * FeedCredentials delivers credentials to an OpenVPN tunnel waiting on an auth
 * prompt. fullPassword must already be basePassword + the 6-digit TOTP code,
 * combined by the caller (the GUI prompts for the code on every connect).
 * 
 * response answers a challenge/response prompt (see the auth_prompt event's
 * challenge_kind): for a "dynamic" (CRV1) prompt it's the entire reply and
 * fullPassword is ignored; for a "static" (SCRV1) prompt it's paired with
 * fullPassword. Pass "" for a plain prompt.
 * @param {string} tunnelName
 * @param {string} username
 * @param {string} fullPassword
 * @param {string} response
 * @returns {$CancellablePromise<void>}
 */
export function FeedCredentials(tunnelName, username, fullPassword, response) {
    return $Call.ByID(549903296, tunnelName, username, fullPassword, response);
}

/**
 * GetConfigText returns the stored tunnel config as text. For OpenVPN tunnels
 * the raw .ovpn content is returned; for WireGuard the serialized INI form.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigText(name) {
    return $Call.ByID(2800041251, name);
}

/**
 * GetConnectionHistory returns the recorded VPN sessions, newest first.
 * Returns an empty slice (never nil) so the frontend doesn't have to special-case
 * "no history yet" vs. "load failed".
 * @returns {$CancellablePromise<history$0.Session[]>}
 */
export function GetConnectionHistory() {
    return $Call.ByID(4142379542).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetCurrentSSID returns the SSID the user is currently connected to,
 * or "" if not connected to a Wi-Fi network. Read on demand — no IPC, no
 * state. The Wi-Fi Rules UI uses this for a live "Currently on:" badge.
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentSSID() {
    return $Call.ByID(1781422564);
}

/**
 * GetRoutingTable returns the current OS routing table.
 * @returns {$CancellablePromise<$models.RouteEntry[]>}
 */
export function GetRoutingTable() {
    return $Call.ByID(2660289744).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetSavedCredentials loads the cached OpenVPN credentials for tunnelName from
 * the Keychain (if any). Returns nil without error when nothing is stored — the
 * caller should treat a nil result as "no saved creds, show empty fields".
 * @param {string} tunnelName
 * @returns {$CancellablePromise<$models.SavedCredentials | null>}
 */
export function GetSavedCredentials(tunnelName) {
    return $Call.ByID(1122228093, tunnelName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<storage$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(1159302687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetStatus queries the helper for the current connection status. IPC errors
 * are surfaced to the caller — the frontend needs to distinguish "helper says
 * disconnected" from "helper unreachable".
 * @returns {$CancellablePromise<$models.ConnectionStatus | null>}
 */
export function GetStatus() {
    return $Call.ByID(3347375428).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetTunnelDetail returns the full WireGuardConfig for a tunnel. Used by the
 * detail pane to show allowed IPs, DNS, public keys, etc.
 * @param {string} name
 * @returns {$CancellablePromise<domain$0.WireGuardConfig | null>}
 */
export function GetTunnelDetail(name) {
    return $Call.ByID(881582661, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetTunnelLatency returns round-trip latency in ms for the named tunnel.
 * 
 * When connected: pings the tunnel's DNS servers (inner VPN gateway) — avoids
 * the full-tunnel loop where pinging the public endpoint routes back through
 * the tunnel itself and never gets a reply.
 * 
 * When disconnected: pings the public endpoint directly, which gives a useful
 * pre-connection latency estimate even without an active tunnel.
 * 
 * Returns -1 if unreachable.
 * @param {string} name
 * @returns {$CancellablePromise<number>}
 */
export function GetTunnelLatency(name) {
    return $Call.ByID(3473741598, name);
}

/**
 * GetTunnelMeta returns per-tunnel metadata (auto-reconnect flag etc.).
 * @param {string} name
 * @returns {$CancellablePromise<storage$0.TunnelMeta | null>}
 */
export function GetTunnelMeta(name) {
    return $Call.ByID(402927985, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetVersion returns the current app version string.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(2377345862);
}

/**
 * GetWifiRules returns the persisted Wi-Fi auto-connect rules. Defaults
 * (feature disabled, empty maps) on first run.
 * @returns {$CancellablePromise<wifi$0.Rules | null>}
 */
export function GetWifiRules() {
    return $Call.ByID(2048144510).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ImportConfig parses, validates, and saves a tunnel config under the given
 * name. Returns a TunnelInfo for optimistic UI display.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportConfig(name, content) {
    return $Call.ByID(188679809, name, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * ImportFile dispatches to the correct importer based on the source filename's
 * extension: .ovpn → OpenVPN, everything else → WireGuard. Used by the native
 * file-drop / picker paths which know the original filename.
 * @param {string} name
 * @param {string} content
 * @param {string} filename
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportFile(name, content, filename) {
    return $Call.ByID(2721946621, name, content, filename).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * ImportFoundConfigs reads and imports the .conf files at the given absolute
 * paths. Returns per-file results reusing the ZipImportResult shape.
 * @param {string[]} paths
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportFoundConfigs(paths) {
    return $Call.ByID(1596298812, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * ImportOVPN validates and stores a raw OpenVPN config under the given name,
 * writing the .ovpn file plus a .meta.json marking the tunnel as OpenVPN.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportOVPN(name, content) {
    return $Call.ByID(3345483956, name, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * ImportQRFromBytes decodes a QR code from raw image bytes and imports the
 * WireGuard config under the given name. Used by the file-picker path where
 * the browser API provides bytes rather than a filesystem path.
 * @param {string} data
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ImportQRFromBytes(data, name) {
    return $Call.ByID(615179959, data, name);
}

/**
 * ImportQRFromPath reads an image file, decodes its QR code, and imports the
 * WireGuard config under the given name.
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ImportQRFromPath(path, name) {
    return $Call.ByID(2642035939, path, name);
}

/**
 * ImportZip extracts all .conf and .ovpn files from a zip archive and imports
 * each one. Returns per-file results; an error is only returned for zip-level
 * failures.
 * @param {string} path
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZip(path) {
    return $Call.ByID(2515408722, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * ImportZipData imports a zip supplied as raw bytes (used by the file picker,
 * which provides a File object rather than a filesystem path).
 * @param {string} data
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZipData(data) {
    return $Call.ByID(368497186, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * IsHelperReady reports whether the helper IPC client is connected.
 * Used by the frontend on mount to avoid relying on events that may have
 * fired before the listener was registered.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsHelperReady() {
    return $Call.ByID(3400283157);
}

/**
 * ListTunnels returns every stored tunnel with its summary info.
 * 
 * The active-tunnel marker used to come from an IPC round-trip on every call.
 * That made the tray's rebuild-menu path slow when it was being invoked on
 * the status event stream. The frontend now learns the active tunnel from
 * the status event itself, and the tray caches it internally — so this
 * function stays fully local (disk-only, no IPC) and returns IsConnected
 * purely as a best-effort flag based on a single active-name probe that is
 * safe to skip entirely on slow paths.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnels() {
    return $Call.ByID(3011645541).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * ListTunnelsLocal returns stored tunnels WITHOUT asking the helper which one
 * is active — callers that already know the active name (e.g. the system
 * tray, which tracks it from the status event stream) should use this to
 * avoid an IPC round-trip on every refresh. IsConnected is always false in
 * the returned slice; the caller is responsible for applying its own
 * active-name match.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnelsLocal() {
    return $Call.ByID(3553304200).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * OpenURL opens a URL in the default browser. Only an explicit allowlist of
 * known-safe URLs is accepted to prevent a compromised frontend from
 * redirecting the user to an attacker-controlled GitHub page.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(4258619583, url);
}

/**
 * ReadFile reads a file from disk (used by native file drop). Returns the
 * content as a string so the frontend can handle name conflicts before import.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(2692059968, path);
}

/**
 * ReconcileHistoryFromStatus syncs the history's open-session map against the
 * list of active tunnels reported by the helper. Used by the event bridge so
 * helper-driven Connect / Disconnect (auto-reconnect on wake, health-check
 * recovery, etc.) is recorded too — not just the buttons in the GUI.
 * 
 * reason classifies sessions that disappeared since the last call:
 *   - "" : default — store as "reconnect"
 *   - "health_check" : helper detected a stale handshake and is re-bringing it up
 * 
 * rxByTunnel/txByTunnel let the caller forward last-known counters from the
 * status event itself; missing keys default to 0.
 * @param {string[]} activeNames
 * @param {{ [_ in string]?: number }} rxByTunnel
 * @param {{ [_ in string]?: number }} txByTunnel
 * @param {string} disappearReason
 * @returns {$CancellablePromise<void>}
 */
export function ReconcileHistoryFromStatus(activeNames, rxByTunnel, txByTunnel, disappearReason) {
    return $Call.ByID(345336368, activeNames, rxByTunnel, txByTunnel, disappearReason);
}

/**
 * RenameTunnel changes a tunnel's name. Rejects rename of the connected
 * tunnel since the interface name is derived from it. For OpenVPN tunnels,
 * also migrates any Keychain-stored credentials to the new name — otherwise
 * they're silently orphaned under the old name (GetSavedCredentials(newName)
 * comes back empty, forcing the user to re-enter them, while the stale
 * old-name entry lingers in the Keychain forever with no deletion path).
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTunnel(oldName, newName) {
    return $Call.ByID(2410860754, oldName, newName);
}

/**
 * ResizeToFit sizes the window to snugly fit the given number of tunnels.
 * 
 * Pixel constants mirror the CSS:
 * 
 * 	titlebar : 50  (InvisibleTitleBarHeight)
 * 	header   : 20  (list-header padding + h2)
 * 	search   : 36  (search-box 24px input + 12px padding)
 * 	row      : 29  (tunnel-item 28px + 1px margin)
 * 	listpad  :  8  (list-items bottom padding)
 * 	footer   : 84  (2×28px buttons + gaps + border + padding)
 * @param {number} tunnelCount
 * @returns {$CancellablePromise<void>}
 */
export function ResizeToFit(tunnelCount) {
    return $Call.ByID(3811485246, tunnelCount);
}

/**
 * RunDNSLeakTest performs a DNS leak test using the currently active tunnel's
 * DNS servers as the expected (VPN) resolvers. If no tunnel is connected, the
 * expected set is empty — all detected resolvers will be flagged as leaks.
 * @returns {$CancellablePromise<$models.DNSLeakResult | null>}
 */
export function RunDNSLeakTest() {
    return $Call.ByID(2844578013).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * RunUpdate performs the update. If installed via Homebrew, runs brew upgrade.
 * Otherwise downloads and installs directly from GitHub Releases.
 * @param {update$0.UpdateInfo | null} info
 * @returns {$CancellablePromise<void>}
 */
export function RunUpdate(info) {
    return $Call.ByID(2979792246, info);
}

/**
 * SaveCredentials stores OpenVPN credentials (username + base password) in
 * the Keychain. The TOTP code is never stored — only the static base
 * password the user enters once.
 * 
 * Done directly in the GUI process (not via IPC to the root helper), same as
 * GetSavedCredentials/DeleteCredentials/the rename-migration path below —
 * Keychain access works fine from here, and previously being the ONE
 * credentials call routed through the helper meant the item got written by
 * root (which macOS's Security framework, with no per-user login-keychain
 * context to target, silently defaults to the admin-managed "System"
 * keychain) while every read happened here as the regular user — a
 * cross-keychain mismatch that made macOS demand an administrator password
 * to read back a per-user VPN credential on every single connect.
 * @param {string} tunnelName
 * @param {string} username
 * @param {string} basePassword
 * @returns {$CancellablePromise<void>}
 */
export function SaveCredentials(tunnelName, username, basePassword) {
    return $Call.ByID(654559795, tunnelName, username, basePassword);
}

/**
 * SaveSettings persists the settings file AND applies any side effects:
 * currently, pushing the new log level to both the GUI's slog handler and
 * the helper's slog handler. Without those side effects a user lowering the
 * level to Debug wouldn't see any new records — the saved file would match
 * the UI but the running process would still be at Info.
 * @param {storage$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(4282610742, settings);
}

/**
 * SaveTunnelMeta persists per-tunnel metadata. The frontend only sends the
 * fields it knows about (auto_reconnect, notes), so we read the existing meta
 * first and preserve any fields the caller didn't set — in particular Protocol,
 * which would otherwise be blanked out and cause an OpenVPN tunnel to be
 * treated as WireGuard on the next load.
 * @param {string} name
 * @param {storage$0.TunnelMeta} meta
 * @returns {$CancellablePromise<void>}
 */
export function SaveTunnelMeta(name, meta) {
    return $Call.ByID(3363409440, name, meta);
}

/**
 * SaveWifiRules persists the rules and pushes them to the live monitor so
 * the next SSID poll uses the new configuration without an app restart.
 * @param {wifi$0.Rules} rules
 * @returns {$CancellablePromise<void>}
 */
export function SaveWifiRules(rules) {
    return $Call.ByID(3250439057, rules);
}

/**
 * ScanForWireGuardConfigs returns existing WireGuard configs found on the
 * filesystem that haven't been imported into LockPlus yet.
 * @returns {$CancellablePromise<$models.FoundConfig[]>}
 */
export function ScanForWireGuardConfigs() {
    return $Call.ByID(2588850719).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * SetApp injects the Wails app for dialog access.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1847627805, app);
}

/**
 * SetDNSProtection asks the helper to lock DNS to the active tunnel's servers.
 * When enabling, we look up the active tunnel's DNS list from local storage
 * and pass it along (the helper never touches user-space storage).
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDNSProtection(enabled) {
    return $Call.ByID(4043511030, enabled);
}

/**
 * SetHealthCheck enables or disables the tunnel health check monitor.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetHealthCheck(enabled) {
    return $Call.ByID(1651406124, enabled);
}

/**
 * SetKillSwitch asks the helper to enable or disable the firewall kill switch.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetKillSwitch(enabled) {
    return $Call.ByID(353876962, enabled);
}

/**
 * SetLogLevel updates both the GUI's and the helper's slog level
 * immediately. Exposed as a Wails method so the Settings view can call
 * it without waiting for a full SaveSettings round trip.
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(2960530306, level);
}

/**
 * SetPinInterface enables or disables -ifscope bypass route pinning.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPinInterface(enabled) {
    return $Call.ByID(2423150392, enabled);
}

/**
 * SetWindow injects the main window so ResizeToFit can adjust its height.
 * @param {application$0.WebviewWindow | null} win
 * @returns {$CancellablePromise<void>}
 */
export function SetWindow(win) {
    return $Call.ByID(3841803210, win);
}

/**
 * TunnelExists reports whether a tunnel with the given name is stored.
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function TunnelExists(name) {
    return $Call.ByID(1886151096, name);
}

/**
 * UpdateConfig parses, validates, and overwrites an existing tunnel's config.
 * Rejects edits of the connected tunnel. Routes to the OpenVPN path for .ovpn
 * tunnels so the raw config is saved without WireGuard parsing.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(name, content) {
    return $Call.ByID(3520953781, name, content);
}

/**
 * ValidateConfig parses and validates a raw config string. Returns a list of
 * human-readable error messages, or nil if the config is valid.
 * @param {string} content
 * @returns {$CancellablePromise<string[]>}
 */
export function ValidateConfig(content) {
    return $Call.ByID(3943944654, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = tunnel$0.ConflictInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = update$0.UpdateInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = history$0.Session.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.RouteEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.SavedCredentials.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = storage$0.Settings.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = domain$0.ConnectionStatus.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = domain$0.WireGuardConfig.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = storage$0.TunnelMeta.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = wifi$0.Rules.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $models.TunnelInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.ZipImportResult.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $Create.Array($$createType21);
const $$createType26 = $models.DNSLeakResult.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $models.FoundConfig.createFrom;
const $$createType29 = $Create.Array($$createType28);
