// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Rules defines WiFi auto-connect behavior.
 */
export class Rules {
    /**
     * Creates a new Rules instance.
     * @param {Partial<Rules>} [$$source = {}] - The source object to create the Rules.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("default_tunnel" in $$source)) {
            /**
             * Tunnel to connect on untrusted networks
             * @member
             * @type {string}
             */
            this["default_tunnel"] = "";
        }
        if (!("auto_connect_untrusted" in $$source)) {
            /**
             * Connect VPN on unknown SSIDs
             * @member
             * @type {boolean}
             */
            this["auto_connect_untrusted"] = false;
        }
        if (!("trusted_ssids" in $$source)) {
            /**
             * SSIDs where VPN is NOT needed
             * @member
             * @type {string[]}
             */
            this["trusted_ssids"] = [];
        }
        if (!("ssid_tunnel_map" in $$source)) {
            /**
             * SSID → specific tunnel name
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["ssid_tunnel_map"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rules instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rules}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trusted_ssids" in $$parsedSource) {
            $$parsedSource["trusted_ssids"] = $$createField3_0($$parsedSource["trusted_ssids"]);
        }
        if ("ssid_tunnel_map" in $$parsedSource) {
            $$parsedSource["ssid_tunnel_map"] = $$createField4_0($$parsedSource["ssid_tunnel_map"]);
        }
        return new Rules(/** @type {Partial<Rules>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
