// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConflictInfo describes a routing conflict with an existing interface.
 */
export class ConflictInfo {
    /**
     * Creates a new ConflictInfo instance.
     * @param {Partial<ConflictInfo>} [$$source = {}] - The source object to create the ConflictInfo.
     */
    constructor($$source = {}) {
        if (!("interface_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface_name"] = "";
        }
        if (!("owner" in $$source)) {
            /**
             * "WireGuide", "Tailscale", "WireGuard", "Unknown"
             * @member
             * @type {string}
             */
            this["owner"] = "";
        }
        if (!("overlapping_ips" in $$source)) {
            /**
             * CIDRs that overlap
             * @member
             * @type {string[]}
             */
            this["overlapping_ips"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overlapping_ips" in $$parsedSource) {
            $$parsedSource["overlapping_ips"] = $$createField2_0($$parsedSource["overlapping_ips"]);
        }
        return new ConflictInfo(/** @type {Partial<ConflictInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
