//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../../../steiale/wireguide/internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gui$0 from "../../../../steiale/wireguide/internal/gui/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ipc$0 from "../../../../steiale/wireguide/internal/ipc/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "auth_prompt": $$createType0,
        "files-dropped": $$createType1,
        "helper": $$createType2,
        "log": $$createType3,
        "reconnect": $$createType4,
        "status": $$createType5,
    }));
}

// Private type creation functions
const $$createType0 = ipc$0.AuthPromptEventPayload.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = gui$0.HelperEvent.createFrom;
const $$createType3 = ipc$0.LogEntry.createFrom;
const $$createType4 = gui$0.ReconnectEvent.createFrom;
const $$createType5 = domain$0.ConnectionStatus.createFrom;

configure();
