// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as domain$0 from "../../../../steiale/wireguide/internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as gui$0 from "../../../../steiale/wireguide/internal/gui/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as ipc$0 from "../../../../steiale/wireguide/internal/ipc/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "files-dropped": { [_ in string]?: any };
            "helper": gui$0.HelperEvent;
            "helper_reset": {};
            "log": ipc$0.LogEntry;
            "reconnect": gui$0.ReconnectEvent;
            "status": domain$0.ConnectionStatus;
        }
    }
}
