//go:build darwin

package network

import (
	"fmt"
	"log/slog"
	"net"
	"os/exec"
	"strings"
	"sync"
	"time"

	"golang.zx2c4.com/wireguard/wgctrl"
)

// DarwinManager implements NetworkManager for macOS, modeled after wg-quick's
// darwin.bash script (github.com/WireGuard/wireguard-tools/src/wg-quick/darwin.bash).
type DarwinManager struct {
	mu sync.Mutex

	// DNS state — saved per service (matches wg-quick collect_new_service_dns).
	// wg-quick sets DNS on EVERY network service, not just the primary one,
	// because macOS can switch primary between Wi-Fi and Ethernet mid-session.
	savedDNS    map[string][]string // service name → original DNS list
	savedSearch map[string][]string // service name → original search domains
	dnsActive   bool

	// Endpoint bypass route state — tracked for cleanup.
	bypassEndpoints []string // IPs we added host routes for

	// Reapply context — stashed during Connect so the route monitor can
	// re-run bypass/DNS/MTU on network changes without needing a config reference.
	lastIface     string
	lastEndpoints []string
	lastDNS       []string
	lastMTU       int
	// lastGatewayV4/V6 remember the upstream default gateway we last anchored
	// our bypass routes to. reapply() compares the live gateway against these
	// and skips the expensive delete+readd cycle if they haven't changed.
	// This is critical: without it, spurious RTM events (including ones
	// generated by our own `route add` commands during Connect) would cause
	// reapply to delete and re-install bypass routes in a tight loop,
	// creating brief windows where encrypted WG packets loop through the
	// tunnel itself and the connection appears dead.
	lastGatewayV4 string
	lastGatewayV6 string
	// lastHasV4Default/V6Default remember whether AddRoutes hijacked the
	// default route for each address family. reapply() uses these to skip
	// bypass routes for families that weren't actually hijacked.
	lastHasV4Default bool
	lastHasV6Default bool
	// lastUpstreamIface is the physical interface (e.g. en0, en5) cached
	// before split routes are installed. Used by addBypassForIP to pin
	// bypass routes with -ifscope, preventing flapping on dual-network setups.
	// Only populated when pinInterface is true.
	lastUpstreamIface string
	// pinInterface controls whether bypass routes use -ifscope to pin
	// to the upstream interface. Disabled by default.
	pinInterface bool

	// Route monitor (wg-quick monitor_daemon equivalent) — only runs for full tunnel.
	monitor *routeMonitor
}

// SetPinInterface enables or disables -ifscope bypass route pinning.
func (m *DarwinManager) SetPinInterface(enabled bool) {
	m.mu.Lock()
	m.pinInterface = enabled
	if !enabled {
		m.lastUpstreamIface = ""
	}
	m.mu.Unlock()
	slog.Info("pin interface toggled", "enabled", enabled)
}

func NewPlatformManager() NetworkManager {
	return &DarwinManager{
		savedDNS:    make(map[string][]string),
		savedSearch: make(map[string][]string),
	}
}

// AssignAddress uses wg-quick's form: `ifconfig <if> inet <ip/cidr> <ip> alias`.
// For IPv6: `ifconfig <if> inet6 <ip/cidr> alias` (no netmask).
func (m *DarwinManager) AssignAddress(ifaceName string, addresses []string) error {
	for _, addr := range addresses {
		ip, _, err := net.ParseCIDR(addr)
		if err != nil {
			return fmt.Errorf("invalid address %q: %w", addr, err)
		}
		if ip.To4() != nil {
			// IPv4: ifconfig <if> inet <cidr> <ip> alias
			if err := run("ifconfig", ifaceName, "inet", addr, ip.String(), "alias"); err != nil {
				return fmt.Errorf("assigning address %s: %w", addr, err)
			}
		} else {
			// IPv6: ifconfig <if> inet6 <cidr> alias
			if err := run("ifconfig", ifaceName, "inet6", addr, "alias"); err != nil {
				return fmt.Errorf("assigning address %s: %w", addr, err)
			}
		}
	}
	return nil
}

// SetMTU uses dynamic detection (wg-quick algorithm): default interface MTU
// minus 80 bytes (40 IPv6 + 8 UDP + 32 WireGuard header overhead).
// Falls back to 1420 if detection fails.
func (m *DarwinManager) SetMTU(ifaceName string, mtu int) error {
	if mtu <= 0 {
		// Auto-detect from default interface
		defaultIf := getDefaultInterface()
		upstreamMTU := 1500
		if defaultIf != "" {
			if v := getInterfaceMTU(defaultIf); v > 0 {
				upstreamMTU = v
			}
		}
		mtu = upstreamMTU - 80
		if mtu < 1280 { // IPv6 minimum
			mtu = 1280
		}
	}
	// Idempotent: skip ifconfig if the interface already has the target MTU.
	// wg-quick's set_mtu_up performs the same check.
	if current := getInterfaceMTU(ifaceName); current == mtu {
		m.mu.Lock()
		m.lastMTU = mtu
		m.mu.Unlock()
		return nil
	}
	if err := run("ifconfig", ifaceName, "mtu", fmt.Sprintf("%d", mtu)); err != nil {
		return err
	}
	m.mu.Lock()
	m.lastMTU = mtu
	m.mu.Unlock()
	return nil
}

func (m *DarwinManager) BringUp(ifaceName string) error {
	return run("ifconfig", ifaceName, "up")
}

// AddRoutes installs routes for AllowedIPs. For /0 (full tunnel) it uses
// the split-route trick + endpoint bypass. Routes are added longest-prefix
// first to avoid transient conflicts (wg-quick's sort -nr -k 2 -t /).
func (m *DarwinManager) AddRoutes(ifaceName string, allowedIPs []string, fullTunnel bool, endpoints []string, tableCfg string, fwmarkCfg string) error {
	if strings.EqualFold(tableCfg, "off") {
		slog.Info("Table=off: skipping route installation", "interface", ifaceName)
		return nil
	}
	// Sort by prefix length descending (longest first)
	sorted := sortAllowedIPs(allowedIPs)

	hasV4Default := false
	hasV6Default := false
	for _, cidr := range sorted {
		isV6 := strings.Contains(cidr, ":")
		if cidr == "0.0.0.0/0" {
			hasV4Default = true
			continue
		}
		if cidr == "::/0" {
			hasV6Default = true
			continue
		}
		// Non-default route: skip if already pointing at this interface (idempotent)
		family := "-inet"
		if isV6 {
			family = "-inet6"
		}
		if existing, _ := runOut("route", "-n", "get", family, cidr); routeUsesInterface(existing, ifaceName) {
			continue
		}
		if err := run("route", "-q", "-n", "add", family, cidr, "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding route %s: %w", cidr, err)
		}
	}

	// Cache the upstream interface BEFORE installing split routes — after
	// split routes, route-get would return utun instead of the physical iface.
	// Only when pinInterface is enabled (dual-network stability).
	m.mu.Lock()
	pin := m.pinInterface
	m.mu.Unlock()
	if pin {
		upstreamIface := getDefaultInterface()
		m.mu.Lock()
		m.lastUpstreamIface = upstreamIface
		m.mu.Unlock()
	}

	// Install default routes using the split trick
	if hasV4Default {
		if err := run("route", "-q", "-n", "add", "-inet", "0.0.0.0/1", "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding 0.0.0.0/1: %w", err)
		}
		if err := run("route", "-q", "-n", "add", "-inet", "128.0.0.0/1", "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding 128.0.0.0/1: %w", err)
		}
	}
	if hasV6Default {
		if err := run("route", "-q", "-n", "add", "-inet6", "::/1", "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding ::/1: %w", err)
		}
		if err := run("route", "-q", "-n", "add", "-inet6", "8000::/1", "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding 8000::/1: %w", err)
		}
	}

	// Add endpoint bypass routes ONLY for the families whose default route
	// we actually hijacked. If a peer endpoint is IPv6 but AllowedIPs only
	// contains 0.0.0.0/0 (IPv4-only full tunnel), the IPv6 default route is
	// untouched — WG packets to the IPv6 peer still flow naturally through
	// the original IPv6 gateway, so NO bypass is needed (and adding one
	// would blackhole a perfectly good path).
	//
	// `endpoints` here are ALREADY-RESOLVED IP LITERALS — the caller
	// (connect_phases) resolved them via the wireguard-go engine at a
	// moment where the tunnel routes were not yet in place. We must never
	// DNS-resolve here, because by this point the /1 split routes above
	// would route the DNS query back through utun, creating a loop.
	//
	// Cache the upstream gateway per family once — one netstat call per
	// family instead of one per endpoint IP.
	var gwV4, gwV6 string
	var gwV4Err, gwV6Err error
	if hasV4Default {
		gwV4, gwV4Err = getDefaultGatewayFor(false)
	}
	if hasV6Default {
		gwV6, gwV6Err = getDefaultGatewayFor(true)
	}
	for _, ipStr := range endpoints {
		if ipStr == "" {
			continue
		}
		ip := net.ParseIP(ipStr)
		if ip == nil {
			slog.Warn("skipping invalid endpoint IP", "ip", ipStr)
			continue
		}
		// Only bypass this endpoint if its family is actually hijacked.
		// See comment above — mis-bypassing a v6 endpoint on a v4-only
		// hijack would blackhole an otherwise-working path.
		isV6 := ip.To4() == nil
		if isV6 && !hasV6Default {
			continue
		}
		if !isV6 && !hasV4Default {
			continue
		}
		if err := m.addBypassForIP(ipStr, gwV4, gwV6, gwV4Err, gwV6Err); err != nil {
			slog.Warn("endpoint bypass route failed", "ip", ipStr, "error", err)
		}
	}

	// Snapshot the current upstream gateway so reapply() can detect genuine
	// changes (Wi-Fi switch etc.) and ignore spurious RTM events.
	currentV4, _ := getDefaultGatewayFor(false)
	currentV6, _ := getDefaultGatewayFor(true)

	// Stash context for reapply on network changes.
	m.mu.Lock()
	m.lastIface = ifaceName
	m.lastEndpoints = append([]string(nil), endpoints...)
	m.lastHasV4Default = hasV4Default
	m.lastHasV6Default = hasV6Default
	m.lastGatewayV4 = currentV4
	m.lastGatewayV6 = currentV6
	m.mu.Unlock()

	// Start route monitor for full-tunnel mode. Without this, switching Wi-Fi
	// networks would leave the endpoint bypass route pointing at the stale
	// gateway and break the tunnel (wg-quick handles this via monitor_daemon).
	//
	// Start is delayed by 2 seconds so that the RTM_* events emitted by our
	// own `route add` commands above (and any OS-driven chatter immediately
	// after the interface comes up) don't trigger a spurious reapply in the
	// critical handshake window. reapply() itself also gates on
	// lastGatewayV4/V6 changes, so this delay is belt-and-suspenders — but
	// cheap insurance against a class of timing bugs.
	// M4: Start route monitor not only for full-tunnel, but also when DNS is
	// configured or endpoints exist in split-tunnel mode. DNS can be disrupted
	// by network changes even in split-tunnel mode, and endpoint bypass routes
	// (if any) need the same gateway-change tracking.
	// H1: lastDNS is mutated by SetDNS/RestoreDNS under m.mu, so the read here
	// must happen under the lock too.
	m.mu.Lock()
	hasDNS := len(m.lastDNS) > 0
	m.mu.Unlock()
	needsMonitor := fullTunnel || hasDNS
	if needsMonitor {
		if m.monitor == nil {
			m.monitor = newRouteMonitor(m.reapply)
		}
		mon := m.monitor
		go func() {
			time.Sleep(2 * time.Second)
			mon.Start()
		}()
	}

	return nil
}

// reapply is invoked by the route monitor on network change events.
// It re-runs the parts of Connect that depend on the upstream default gateway.
//
// CRITICAL: This function only does work when the upstream default gateway
// has ACTUALLY changed since the last time we pinned our bypass routes. The
// route monitor fires on any RTM_* event, including ones generated by our
// own `route add` commands during Connect and by unrelated OS chatter. Doing
// a full delete+readd cycle on every spurious event creates a routing loop
// window where WG encrypted packets go through the tunnel itself, and the
// connection appears dead. Comparing against lastGatewayV4/V6 turns those
// spurious firings into cheap no-ops.
func (m *DarwinManager) reapply() {
	m.mu.Lock()
	iface := m.lastIface
	oldEndpoints := append([]string(nil), m.lastEndpoints...)
	dns := m.lastDNS
	mtu := m.lastMTU
	prevV4 := m.lastGatewayV4
	prevV6 := m.lastGatewayV6
	hasV4 := m.lastHasV4Default
	hasV6 := m.lastHasV6Default
	m.mu.Unlock()

	if iface == "" {
		return
	}

	// wg-quick's set_endpoint_direct_route re-reads endpoints from
	// `wg show <iface> endpoints` on every RTM event, because wireguard-go
	// can roam to a different endpoint IP after a handshake. We do the
	// same via wgctrl so bypass routes track the actual peer endpoint.
	liveEndpoints := collectLiveEndpoints(iface)
	if len(liveEndpoints) == 0 {
		// Interface may be gone — monitor loop will break on the next
		// ifconfig check. Use cached endpoints as fallback.
		liveEndpoints = oldEndpoints
	}

	// Probe the current upstream gateway for each family. These values are
	// reused below when re-installing bypass routes, avoiding a redundant
	// second pair of netstat calls.
	currentV4, currentV4Err := getDefaultGatewayFor(false)
	currentV6, currentV6Err := getDefaultGatewayFor(true)

	gatewayChanged := currentV4 != prevV4 || currentV6 != prevV6

	// Detect endpoint roaming: compare live endpoints against the set we
	// have bypass routes for. wg-quick diffs old vs new and only touches
	// changed entries; we do the same.
	endpointsChanged := !stringSetEqual(oldEndpoints, liveEndpoints)

	needBypassUpdate := (hasV4 || hasV6) && (gatewayChanged || endpointsChanged)

	if !needBypassUpdate {
		// No bypass work needed, but still re-apply DNS — macOS can
		// reassign DNS when switching network services.
		if len(dns) > 0 {
			_ = m.applyDNS(dns)
		}
		return
	}

	slog.Info("route monitor: reapplying bypass routes",
		"iface", iface,
		"gateway_changed", gatewayChanged,
		"endpoints_changed", endpointsChanged,
		"prev_v4", prevV4, "current_v4", currentV4,
		"prev_v6", prevV6, "current_v6", currentV6,
		"old_endpoints", oldEndpoints, "live_endpoints", liveEndpoints)

	// Build sets for diffing (mirrors wg-quick's old_endpoints / ENDPOINTS logic).
	oldSet := make(map[string]bool, len(oldEndpoints))
	for _, ep := range oldEndpoints {
		oldSet[ep] = true
	}
	newSet := make(map[string]bool, len(liveEndpoints))
	for _, ep := range liveEndpoints {
		newSet[ep] = true
	}

	// If gateway changed, delete ALL old bypass routes (wg-quick: remove_all_old=1).
	// If only endpoints changed, delete only endpoints no longer in the live set.
	m.mu.Lock()
	oldBypass := m.bypassEndpoints
	m.bypassEndpoints = nil
	m.mu.Unlock()

	for _, ip := range oldBypass {
		shouldDelete := gatewayChanged || !newSet[ip]
		if !shouldDelete {
			// Still current — keep it in the bypass list without re-adding.
			m.mu.Lock()
			m.bypassEndpoints = append(m.bypassEndpoints, ip)
			m.mu.Unlock()
			continue
		}
		family := "-inet"
		if strings.Contains(ip, ":") {
			family = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", family, ip)
	}

	// Reuse the gateways already probed above — no need for a second pair
	// of netstat calls. If the gateway changed between the probe and now
	// (extremely unlikely), the next RTM event will trigger another reapply.
	newGwV4, newGwV4Err := currentV4, currentV4Err
	newGwV6, newGwV6Err := currentV6, currentV6Err

	// Add bypass routes for endpoints that need (re-)installation:
	// - If gateway changed: all live endpoints (they were all deleted above).
	// - If only endpoints changed: only newly appeared endpoints.
	for _, ipStr := range liveEndpoints {
		if ipStr == "" {
			continue
		}
		if !gatewayChanged && oldSet[ipStr] {
			// Gateway didn't change and this endpoint already had a valid
			// bypass route (preserved above). Skip.
			continue
		}
		ip := net.ParseIP(ipStr)
		if ip == nil {
			continue
		}
		isV6 := ip.To4() == nil
		if isV6 && !hasV6 {
			continue
		}
		if !isV6 && !hasV4 {
			continue
		}
		if err := m.addBypassForIP(ipStr, newGwV4, newGwV6, newGwV4Err, newGwV6Err); err != nil {
			slog.Warn("reapply: bypass failed", "ip", ipStr, "error", err)
		}
	}

	// Update cached state including upstream interface for bypass -ifscope.
	// Resolve interface outside the lock to avoid blocking on netstat.
	// H2: pinInterface is mutated by SetPinInterface under m.mu, so read it
	// under the lock first.
	m.mu.Lock()
	pinIface := m.pinInterface
	m.mu.Unlock()
	newUpstreamIface := ""
	if pinIface {
		newUpstreamIface = getDefaultInterface()
	}
	m.mu.Lock()
	m.lastEndpoints = append([]string(nil), liveEndpoints...)
	m.lastGatewayV4 = newGwV4
	m.lastGatewayV6 = newGwV6
	m.lastUpstreamIface = newUpstreamIface
	m.mu.Unlock()

	if len(dns) > 0 {
		_ = m.applyDNS(dns)
	}

	if mtu > 0 {
		if current := getInterfaceMTU(iface); current != mtu && current > 0 {
			_ = run("ifconfig", iface, "mtu", fmt.Sprintf("%d", mtu))
		}
	}
}

// collectLiveEndpoints reads the current peer endpoint IPs from the WireGuard
// interface via wgctrl, mirroring wg-quick's `wg show $REAL_INTERFACE endpoints`.
// Returns deduplicated IP strings (no port). Returns nil on any error.
func collectLiveEndpoints(ifaceName string) []string {
	client, err := wgctrl.New()
	if err != nil {
		slog.Debug("collectLiveEndpoints: wgctrl.New failed", "error", err)
		return nil
	}
	defer client.Close()

	dev, err := client.Device(ifaceName)
	if err != nil {
		slog.Debug("collectLiveEndpoints: Device() failed", "iface", ifaceName, "error", err)
		return nil
	}

	seen := make(map[string]bool)
	var eps []string
	for _, peer := range dev.Peers {
		if peer.Endpoint == nil {
			continue
		}
		ip := peer.Endpoint.IP.String()
		if !seen[ip] {
			seen[ip] = true
			eps = append(eps, ip)
		}
	}
	return eps
}

// stringSetEqual returns true if two string slices contain the same elements
// (order-independent).
func stringSetEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	set := make(map[string]int, len(a))
	for _, s := range a {
		set[s]++
	}
	for _, s := range b {
		set[s]--
		if set[s] < 0 {
			return false
		}
	}
	return true
}

// addBypassForIP installs a host route for one already-resolved peer endpoint
// IP, pointing at the upstream default gateway. Without this, encrypted WG
// packets destined for the peer would match the /1 split routes and loop
// back through the tunnel itself.
//
// Gateways are passed in (not resolved here) so the caller can make a single
// netstat call for all IPs in a batch — one per family instead of one per IP.
//
// If the gateway probe failed for a given family, we fall back to wg-quick's
// behaviour of installing a blackhole route, which breaks the loop while
// clearly signalling to the user that handshake is impossible in this state.
func (m *DarwinManager) addBypassForIP(ipStr, gwV4, gwV6 string, gwV4Err, gwV6Err error) error {
	ip := net.ParseIP(ipStr)
	if ip == nil {
		return fmt.Errorf("invalid endpoint IP %q", ipStr)
	}
	isV6 := ip.To4() == nil

	var gw string
	var gwErr error
	family := "-inet"
	if isV6 {
		gw = gwV6
		gwErr = gwV6Err
		family = "-inet6"
	} else {
		gw = gwV4
		gwErr = gwV4Err
	}

	recordBypass := func() {
		m.mu.Lock()
		m.bypassEndpoints = append(m.bypassEndpoints, ipStr)
		m.mu.Unlock()
	}

	if gwErr != nil || gw == "" {
		// No usable upstream gateway → install a blackhole so encrypted WG
		// traffic to this peer doesn't loop through the tunnel.
		loopback := "127.0.0.1"
		if isV6 {
			loopback = "::1"
		}
		_ = run("route", "-q", "-n", "add", family, ipStr, loopback, "-blackhole")
		recordBypass()
		return nil
	}

	// Use the cached upstream interface to pin the bypass route with
	// -ifscope. This prevents macOS from flapping between WiFi and
	// Ethernet when both are active.
	m.mu.Lock()
	iface := m.lastUpstreamIface
	m.mu.Unlock()

	// Try `route add` first, fall back to `route change` if the kernel
	// already has a route for this host (common when reconnecting).
	if iface != "" {
		if err := run("route", "-q", "-n", "add", family, ipStr, "-gateway", gw, "-ifscope", iface); err != nil {
			if err2 := run("route", "-q", "-n", "change", family, ipStr, "-gateway", gw, "-ifscope", iface); err2 != nil {
				// Fallback: try without -ifscope in case the OS rejects it
				slog.Debug("ifscope route failed, falling back to unscoped", "ip", ipStr, "iface", iface)
				if err3 := run("route", "-q", "-n", "add", family, ipStr, "-gateway", gw); err3 != nil {
					if err4 := run("route", "-q", "-n", "change", family, ipStr, "-gateway", gw); err4 != nil {
						return fmt.Errorf("bypass route %s via %s (ifscope %s failed, unscoped also failed): %v", ipStr, gw, iface, err4)
					}
				}
			}
		}
	} else {
		if err := run("route", "-q", "-n", "add", family, ipStr, "-gateway", gw); err != nil {
			if err2 := run("route", "-q", "-n", "change", family, ipStr, "-gateway", gw); err2 != nil {
				return fmt.Errorf("bypass route %s via %s: add=%v, change=%v", ipStr, gw, err, err2)
			}
		}
	}
	recordBypass()
	return nil
}

// RemoveRoutes cleans up. wg-quick approach: walk netstat and remove ALL
// routes pointing at this interface, then remove endpoint bypass routes.
// This is more robust than tracking what we added.
func (m *DarwinManager) RemoveRoutes(ifaceName string, allowedIPs []string, fullTunnel bool) error {
	// Stop the route monitor first so its reapply goroutine can't race with
	// teardown. Stop() blocks until any in-flight reapply callback finishes.
	if m.monitor != nil {
		m.monitor.Stop()
	}

	// Remove all routes via this interface (both IPv4 and IPv6)
	m.deleteInterfaceRoutes(ifaceName, "inet")
	m.deleteInterfaceRoutes(ifaceName, "inet6")

	// Snapshot bypass list under the lock, then delete outside.
	m.mu.Lock()
	bypass := m.bypassEndpoints
	m.bypassEndpoints = nil
	m.lastIface = ""
	m.lastEndpoints = nil
	m.lastGatewayV4 = ""
	m.lastGatewayV6 = ""
	m.lastHasV4Default = false
	m.lastHasV6Default = false
	m.mu.Unlock()

	for _, ip := range bypass {
		family := "-inet"
		if strings.Contains(ip, ":") {
			family = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", family, ip)
	}
	return nil
}

// deleteInterfaceRoutes walks netstat for the given family and deletes
// every route whose interface (Netif column) matches ifaceName.
// Also handles the wg-quick IPv6 edge case where Netif=lo0 but Gateway=utunN.
func (m *DarwinManager) deleteInterfaceRoutes(ifaceName, family string) {
	out, err := runOut("netstat", "-nr", "-f", family)
	if err != nil {
		return
	}
	// Parse header to find Destination / Gateway / Netif column positions.
	netifIdx, destIdx, gwIdx := -1, -1, -1
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if netifIdx < 0 {
			// Look for header row
			for i, f := range fields {
				switch f {
				case "Destination":
					destIdx = i
				case "Gateway":
					gwIdx = i
				case "Netif":
					netifIdx = i
				}
			}
			continue
		}
		// Require ALL three columns to be in range before indexing, not just
		// Netif — a malformed header could leave destIdx or gwIdx pointing
		// past the line and crash on field access.
		maxIdx := netifIdx
		if destIdx > maxIdx {
			maxIdx = destIdx
		}
		if gwIdx > maxIdx {
			maxIdx = gwIdx
		}
		if len(fields) <= maxIdx || destIdx < 0 || gwIdx < 0 {
			continue
		}
		dest := fields[destIdx]
		gw := fields[gwIdx]
		netif := fields[netifIdx]

		// Match: Netif is our interface, OR (IPv6 only) Netif is lo* and Gateway is our interface
		match := netif == ifaceName
		if !match && family == "inet6" && strings.HasPrefix(netif, "lo") && gw == ifaceName {
			match = true
		}
		if !match {
			continue
		}

		// Use "default" directly in route delete — macOS `route` understands
		// the keyword and it avoids ambiguity with explicit CIDR notation.
		// No translation needed.
		famFlag := "-inet"
		if family == "inet6" {
			famFlag = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", famFlag, dest)
	}
}

// routeUsesInterface checks `route get` output for an exact match on the
// interface field. Prevents false matches between utun3 / utun33.
func routeUsesInterface(routeOutput []byte, ifaceName string) bool {
	for _, line := range strings.Split(string(routeOutput), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "interface:") {
			name := strings.TrimSpace(strings.TrimPrefix(line, "interface:"))
			return name == ifaceName
		}
	}
	return false
}

// SetDNS sets DNS on ALL network services (matching wg-quick).
// Entries are split into servers (IPs) and search domains (hostnames),
// mirroring wg-quick's `set_dns` which parses `DNS = 1.1.1.1, corp.example.com`
// that way.
//
// Performance: `networksetup -setdnsservers` is synchronous and slow
// (~150–400 ms per call on a typical Mac). With 5 network services (Wi-Fi,
// Ethernet, Bluetooth PAN, Thunderbolt Bridge, iPhone USB) this can add
// 1.5–4 seconds to Connect if done sequentially. We therefore fan out one
// goroutine per service and wait on them in parallel — they touch different
// resources so there's no contention.
func (m *DarwinManager) SetDNS(ifaceName string, entries []string) error {
	if len(entries) == 0 {
		return nil
	}

	services := getAllNetworkServices()
	if len(services) == 0 {
		return fmt.Errorf("no network services found")
	}

	// Check/update `dnsActive` under the lock — this field is also read by
	// RestoreDNS and (potentially) by reapply via applyDNS, so touching it
	// without the lock is a data race.
	m.mu.Lock()
	alreadyActive := m.dnsActive
	m.mu.Unlock()

	// Save original DNS for each service before overriding (only on first apply).
	// Parallelised: each networksetup -getdnsservers call is ~100–200 ms.
	if !alreadyActive {
		type savedEntry struct {
			svc    string
			dns    []string
			search []string
		}
		saved := make([]savedEntry, len(services))
		var wg sync.WaitGroup
		for i, svc := range services {
			i, svc := i, svc
			wg.Add(1)
			go func() {
				defer wg.Done()
				dns, _ := getCurrentDNS(svc)
				search, _ := getCurrentSearchDomains(svc)
				saved[i] = savedEntry{svc: svc, dns: dns, search: search}
			}()
		}
		wg.Wait()
		m.mu.Lock()
		for _, e := range saved {
			m.savedDNS[e.svc] = e.dns
			m.savedSearch[e.svc] = e.search
		}
		m.mu.Unlock()
	}

	// Push the new DNS to every service in parallel.
	m.applyDNSToServices(entries, services)

	// Verify DNS actually took effect on at least one service. macOS can
	// silently fail to apply DNS settings (e.g. permission issues, MDM
	// profiles overriding). Without this check the user thinks VPN DNS
	// is active but traffic goes to their ISP resolver.
	servers, _ := splitDNSEntries(entries)
	if len(servers) > 0 {
		if err := m.verifyDNS(services, servers); err != nil {
			slog.Warn("DNS verification failed", "error", err)
			return fmt.Errorf("DNS applied but verification failed: %w", err)
		}
	}

	// Flush the macOS DNS cache so lookups see the new servers immediately.
	// Without this users can keep hitting stale resolutions for several
	// minutes — wg-quick does this at the end of its set_dns.
	flushDNSCache()

	m.mu.Lock()
	m.lastDNS = entries
	m.dnsActive = true
	m.mu.Unlock()
	return nil
}

// applyDNS pushes DNS servers and search domains to every network service.
// M5: Also captures original DNS for any new network services that weren't
// present when SetDNS was first called, so they can be properly restored.
func (m *DarwinManager) applyDNS(entries []string) error {
	services := getAllNetworkServices()

	// M5: Check for new services that weren't in the original savedDNS map.
	// Collect the list of services needing DNS capture under the lock, then
	// release the lock once, do all network calls, and re-lock once to store.
	var newServices []string
	m.mu.Lock()
	if m.dnsActive {
		for _, svc := range services {
			if _, exists := m.savedDNS[svc]; !exists {
				newServices = append(newServices, svc)
			}
		}
	}
	m.mu.Unlock()

	// Fetch DNS for newly discovered services without holding the lock.
	if len(newServices) > 0 {
		type savedEntry struct {
			svc    string
			dns    []string
			search []string
		}
		fetched := make([]savedEntry, len(newServices))
		var wg sync.WaitGroup
		for i, svc := range newServices {
			i, svc := i, svc
			wg.Add(1)
			go func() {
				defer wg.Done()
				dns, _ := getCurrentDNS(svc)
				search, _ := getCurrentSearchDomains(svc)
				fetched[i] = savedEntry{svc: svc, dns: dns, search: search}
			}()
		}
		wg.Wait()

		m.mu.Lock()
		for _, e := range fetched {
			if _, exists := m.savedDNS[e.svc]; !exists {
				m.savedDNS[e.svc] = e.dns
				m.savedSearch[e.svc] = e.search
				slog.Info("discovered new network service, saving DNS", "service", e.svc)
			}
		}
		m.mu.Unlock()
	}

	m.applyDNSToServices(entries, services)
	flushDNSCache()
	return nil
}

// applyDNSToServices is the shared hot path used by both SetDNS and applyDNS.
// Takes a pre-fetched service list (avoids redundant
// `networksetup -listallnetworkservices` calls) and fans out one goroutine
// per service.
func (m *DarwinManager) applyDNSToServices(entries []string, services []string) {
	servers, search := splitDNSEntries(entries)
	if len(services) == 0 {
		return
	}

	var wg sync.WaitGroup
	for _, svc := range services {
		svc := svc
		wg.Add(1)
		go func() {
			defer wg.Done()
			if len(servers) > 0 {
				args := append([]string{"-setdnsservers", svc}, servers...)
				if err := run("networksetup", args...); err != nil {
					slog.Warn("failed to set DNS on service", "service", svc, "error", err)
				}
			}
			if len(search) > 0 {
				args := append([]string{"-setsearchdomains", svc}, search...)
				if err := run("networksetup", args...); err != nil {
					slog.Warn("failed to set search domains on service", "service", svc, "error", err)
				}
			}
		}()
	}
	wg.Wait()
}

// flushDNSCache tells macOS's mDNSResponder to drop any cached entries so
// lookups see the new DNS servers immediately. Best-effort: errors are not
// propagated because a failed flush is not worth aborting a successful
// Connect over.
func flushDNSCache() {
	_ = run("dscacheutil", "-flushcache")
	_ = run("killall", "-HUP", "mDNSResponder")
}

// splitDNSEntries partitions a mixed DNS list into IP servers and hostname
// search domains, matching wg-quick's parse of `DNS = 1.1.1.1, corp.example.com`.
func splitDNSEntries(entries []string) (servers, search []string) {
	for _, e := range entries {
		e = strings.TrimSpace(e)
		if e == "" {
			continue
		}
		if net.ParseIP(e) != nil {
			servers = append(servers, e)
		} else {
			search = append(search, e)
		}
	}
	return
}

// verifyDNS checks that at least one network service has the expected DNS
// servers applied. macOS can silently drop DNS changes (MDM profiles,
// permission issues, etc.), so we read back and confirm. Retries once
// after a short delay to handle asynchronous DNS propagation.
func (m *DarwinManager) verifyDNS(services, expectedServers []string) error {
	for attempt := 0; attempt < 2; attempt++ {
		if attempt > 0 {
			time.Sleep(500 * time.Millisecond)
		}
		// Check all services in parallel.
		type result struct {
			found bool
		}
		results := make([]result, len(services))
		var wg sync.WaitGroup
		for i, svc := range services {
			i, svc := i, svc
			wg.Add(1)
			go func() {
				defer wg.Done()
				current, err := getCurrentDNS(svc)
				if err != nil || len(current) == 0 {
					return
				}
				for _, got := range current {
					if got == expectedServers[0] {
						results[i].found = true
						return
					}
				}
			}()
		}
		wg.Wait()
		for _, r := range results {
			if r.found {
				return nil
			}
		}
	}
	return fmt.Errorf("DNS server %s not found on any network service after apply", expectedServers[0])
}

// ResetDNSToSystemDefault clears DNS overrides on every network service
// back to DHCP-provided defaults. Used by crash recovery when the process
// has no memory of the pre-crash DNS state. Parallel across services.
func (m *DarwinManager) ResetDNSToSystemDefault() error {
	services := getAllNetworkServices()
	var wg sync.WaitGroup
	for _, svc := range services {
		svc := svc
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := run("networksetup", "-setdnsservers", svc, "Empty"); err != nil {
				slog.Warn("reset DNS servers failed", "service", svc, "error", err)
			}
			if err := run("networksetup", "-setsearchdomains", svc, "Empty"); err != nil {
				slog.Warn("reset search domains failed", "service", svc, "error", err)
			}
		}()
	}
	wg.Wait()
	flushDNSCache()
	return nil
}

// RestoreDNS restores original DNS for every service we touched. Parallel
// across services — each networksetup call is ~200 ms, and with 5+ services
// the serial version added a full second to every Disconnect.
func (m *DarwinManager) RestoreDNS(ifaceName string) error {
	// Snapshot saved state under the lock, then reset it in the same
	// critical section so any racing SetDNS doesn't see a half-cleared
	// view. dnsActive/savedDNS/savedSearch all live under m.mu.
	m.mu.Lock()
	if !m.dnsActive {
		m.mu.Unlock()
		return nil
	}
	savedDNS := m.savedDNS
	savedSearch := m.savedSearch
	m.savedDNS = make(map[string][]string)
	m.savedSearch = make(map[string][]string)
	m.dnsActive = false
	m.lastDNS = nil
	m.mu.Unlock()

	// Fan out networksetup calls in parallel — each is ~200ms, so for 5+
	// services we save multiple seconds vs serial.
	var wg sync.WaitGroup
	for svc, orig := range savedDNS {
		svc, orig := svc, orig
		wg.Add(1)
		go func() {
			defer wg.Done()
			if len(orig) == 0 {
				_ = run("networksetup", "-setdnsservers", svc, "Empty")
			} else {
				args := append([]string{"-setdnsservers", svc}, orig...)
				_ = run("networksetup", args...)
			}
		}()
	}
	for svc, search := range savedSearch {
		svc, search := svc, search
		wg.Add(1)
		go func() {
			defer wg.Done()
			if len(search) == 0 {
				_ = run("networksetup", "-setsearchdomains", svc, "Empty")
			} else {
				args := append([]string{"-setsearchdomains", svc}, search...)
				_ = run("networksetup", args...)
			}
		}()
	}
	wg.Wait()
	flushDNSCache()
	return nil
}

// SavedDNSSnapshot returns the current per-service DNS snapshot for
// persistence to the crash recovery journal. Thread-safe.
func (m *DarwinManager) SavedDNSSnapshot() map[string][]string {
	m.mu.Lock()
	defer m.mu.Unlock()
	if !m.dnsActive || len(m.savedDNS) == 0 {
		return nil
	}
	snapshot := make(map[string][]string, len(m.savedDNS))
	for svc, dns := range m.savedDNS {
		cp := make([]string, len(dns))
		copy(cp, dns)
		snapshot[svc] = cp
	}
	return snapshot
}

// RestoreDNSFromSnapshot restores DNS from a persisted pre-modification
// snapshot. Used during crash recovery when in-memory state is unavailable.
func (m *DarwinManager) RestoreDNSFromSnapshot(preModDNS map[string][]string) error {
	var wg sync.WaitGroup
	for svc, orig := range preModDNS {
		svc, orig := svc, orig
		wg.Add(1)
		go func() {
			defer wg.Done()
			if len(orig) == 0 {
				_ = run("networksetup", "-setdnsservers", svc, "Empty")
			} else {
				args := append([]string{"-setdnsservers", svc}, orig...)
				_ = run("networksetup", args...)
			}
		}()
	}
	wg.Wait()
	flushDNSCache()
	return nil
}

func (m *DarwinManager) Cleanup(ifaceName string) error {
	if m.monitor != nil {
		m.monitor.Stop()
	}
	_ = m.RestoreDNS(ifaceName)
	// Defensive: remove any remaining routes via this interface
	m.deleteInterfaceRoutes(ifaceName, "inet")
	m.deleteInterfaceRoutes(ifaceName, "inet6")

	m.mu.Lock()
	bypass := m.bypassEndpoints
	m.bypassEndpoints = nil
	m.mu.Unlock()

	for _, ip := range bypass {
		family := "-inet"
		if strings.Contains(ip, ":") {
			family = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", family, ip)
	}
	return nil
}

// --- helpers ---

func run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	// Force C locale so parsing English sentinels like "There aren't any DNS Servers"
	// works on non-English macOS systems. wg-quick uses `export LC_ALL=C` at script top.
	cmd.Env = append(cmd.Environ(), "LC_ALL=C", "LANG=C")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w (%s)", name, strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

// runOut runs a command with LC_ALL=C and returns combined output.
// Use for commands where we parse the output.
func runOut(name string, args ...string) ([]byte, error) {
	cmd := exec.Command(name, args...)
	cmd.Env = append(cmd.Environ(), "LC_ALL=C", "LANG=C")
	return cmd.CombinedOutput()
}

// getDefaultGatewayFor returns the IPv4 or IPv6 default gateway, skipping
// link-local entries (link#N) per wg-quick's collect_gateways.
func getDefaultGatewayFor(ipv6 bool) (string, error) {
	family := "inet"
	if ipv6 {
		family = "inet6"
	}
	out, err := runOut("netstat", "-nr", "-f", family)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		if fields[0] != "default" {
			continue
		}
		gw := fields[1]
		// Skip link-local defaults (point-to-point with no gateway IP)
		if strings.HasPrefix(gw, "link#") {
			continue
		}
		return gw, nil
	}
	return "", fmt.Errorf("no default gateway for %s", family)
}

// getDefaultInterface returns the name of the default route's interface
// by parsing the netstat header to locate the Netif column, then scanning
// for the `default` row. Dynamic header parsing handles column-order
// differences across macOS versions; the previous "first lowercase field"
// heuristic returned `awdl0` (AirDrop) instead of `en0` on some machines.
// getRouteInterface returns the interface macOS would use to reach the given
// IP, by parsing `route get <ip>` output. Returns empty string on failure.
func getRouteInterface(ip string) string {
	out, err := runOut("route", "-n", "get", ip)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "interface:") {
			return strings.TrimSpace(strings.TrimPrefix(line, "interface:"))
		}
	}
	return ""
}

func getDefaultInterface() string {
	out, err := runOut("netstat", "-nr", "-f", "inet")
	if err != nil {
		return ""
	}
	netifIdx, destIdx := -1, -1
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		if netifIdx < 0 {
			for i, f := range fields {
				switch f {
				case "Destination":
					destIdx = i
				case "Netif":
					netifIdx = i
				}
			}
			continue
		}
		maxIdx := netifIdx
		if destIdx > maxIdx {
			maxIdx = destIdx
		}
		if destIdx < 0 || netifIdx < 0 || len(fields) <= maxIdx {
			continue
		}
		if fields[destIdx] == "default" {
			return fields[netifIdx]
		}
	}
	return ""
}

// getInterfaceMTU reads the MTU from ifconfig output.
func getInterfaceMTU(ifaceName string) int {
	out, err := runOut("ifconfig", ifaceName)
	if err != nil {
		return 0
	}
	// Format includes "mtu 1500"
	idx := strings.Index(string(out), "mtu ")
	if idx < 0 {
		return 0
	}
	rest := string(out)[idx+4:]
	var mtu int
	fmt.Sscanf(rest, "%d", &mtu)
	return mtu
}

// getAllNetworkServices returns all network services, including disabled ones.
// wg-quick includes disabled services (strips the "*" prefix) so DNS is
// applied/restored uniformly regardless of current enabled state.
func getAllNetworkServices() []string {
	out, err := runOut("networksetup", "-listallnetworkservices")
	if err != nil {
		return nil
	}
	var services []string
	firstLine := true
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if firstLine {
			// First non-empty line is the header ("An asterisk...")
			firstLine = false
			continue
		}
		// Strip leading "*" from disabled services (don't skip them)
		if strings.HasPrefix(line, "*") {
			line = strings.TrimSpace(line[1:])
		}
		if line != "" {
			services = append(services, line)
		}
	}
	return services
}

func getCurrentDNS(service string) ([]string, error) {
	out, err := runOut("networksetup", "-getdnsservers", service)
	if err != nil {
		return nil, err
	}
	output := strings.TrimSpace(string(out))
	if strings.Contains(output, "There aren't any DNS Servers") {
		return nil, nil
	}
	var servers []string
	for _, line := range strings.Split(output, "\n") {
		s := strings.TrimSpace(line)
		if s != "" {
			servers = append(servers, s)
		}
	}
	return servers, nil
}

func getCurrentSearchDomains(service string) ([]string, error) {
	out, err := runOut("networksetup", "-getsearchdomains", service)
	if err != nil {
		return nil, err
	}
	output := strings.TrimSpace(string(out))
	if strings.Contains(output, "There aren't any Search Domains") {
		return nil, nil
	}
	var domains []string
	for _, line := range strings.Split(output, "\n") {
		s := strings.TrimSpace(line)
		if s != "" {
			domains = append(domains, s)
		}
	}
	return domains, nil
}

// sortAllowedIPs sorts CIDRs by prefix length descending (longest first),
// matching wg-quick's `sort -nr -k 2 -t /`. Stable order for determinism.
func sortAllowedIPs(cidrs []string) []string {
	result := make([]string, len(cidrs))
	copy(result, cidrs)

	// Simple insertion sort (lists are small, stability guaranteed)
	for i := 1; i < len(result); i++ {
		cur := result[i]
		curPrefix := prefixLen(cur)
		j := i - 1
		for j >= 0 && prefixLen(result[j]) < curPrefix {
			result[j+1] = result[j]
			j--
		}
		result[j+1] = cur
	}
	return result
}

func prefixLen(cidr string) int {
	idx := strings.Index(cidr, "/")
	if idx < 0 {
		// Bare address without prefix — return 32 for IPv4, 128 for IPv6
		if strings.Contains(cidr, ":") {
			return 128
		}
		return 32
	}
	var n int
	fmt.Sscanf(cidr[idx+1:], "%d", &n)
	return n
}
