// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    ConnectionStatus,
    InterfaceConfig,
    PeerConfig,
    State,
    WireGuardConfig
} from "./models.js";
