// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionStatus is the single source of truth for tunnel connection state
 * across the whole application. It carries both wire-safe fields (strings,
 * JSON-tagged) that are sent to the frontend, and internal fields (time.Time,
 * `json:"-"`) that the reconnect monitor and other backend services use for
 * duration math.
 * 
 * Note that `LastHandshake` is the *formatted age string* (e.g. "5s", "2m 10s")
 * that the frontend displays, while `LastHandshakeTime` is the absolute
 * timestamp used internally. Wire callers see only the former.
 */
export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["interface_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["duration"] = undefined;
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_handshake"] = undefined;
        }
        if (!("has_handshake" in $$source)) {
            /**
             * HasHandshake is true iff the tunnel has at least one peer that has
             * completed a handshake (LastHandshakeTime != zero). The frontend used
             * to derive this from the truthiness of the formatted LastHandshake
             * string, which broke whenever the formatter returned "0s" for a fresh
             * tunnel. Carrying an explicit boolean removes that ambiguity.
             * @member
             * @type {boolean}
             */
            this["has_handshake"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Protocol identifies the VPN backend (WireGuard or OpenVPN). Empty for
             * legacy/WireGuard statuses; the frontend treats empty as WireGuard.
             * @member
             * @type {Protocol | undefined}
             */
            this["protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ActiveTunnels lists the names of all currently connected (or connecting)
             * tunnels. Populated by the multi-tunnel manager so the frontend can show
             * which tunnels are active.
             * @member
             * @type {string[] | undefined}
             */
            this["active_tunnels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Tunnels carries per-tunnel status for multi-tunnel setups. The frontend
             * uses this to show stats for the selected tunnel rather than the "primary".
             * @member
             * @type {ConnectionStatus[] | undefined}
             */
            this["tunnels"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("active_tunnels" in $$parsedSource) {
            $$parsedSource["active_tunnels"] = $$createField11_0($$parsedSource["active_tunnels"]);
        }
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField12_0($$parsedSource["tunnels"]);
        }
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

/**
 * InterfaceConfig represents the [Interface] section of a .conf file.
 */
export class InterfaceConfig {
    /**
     * Creates a new InterfaceConfig instance.
     * @param {Partial<InterfaceConfig>} [$$source = {}] - The source object to create the InterfaceConfig.
     */
    constructor($$source = {}) {
        if (!("private_key" in $$source)) {
            /**
             * Required: Base64-encoded 32-byte key
             * @member
             * @type {string}
             */
            this["private_key"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * Required: CIDR addresses (e.g., "10.0.0.2/24")
             * @member
             * @type {string[]}
             */
            this["address"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: DNS servers and/or search domains
             * @member
             * @type {string[] | undefined}
             */
            this["dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: 0 = auto-detect
             * @member
             * @type {number | undefined}
             */
            this["mtu"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: 0 = random
             * @member
             * @type {number | undefined}
             */
            this["listen_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: routing table
             * @member
             * @type {string | undefined}
             */
            this["table"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: firewall mark
             * @member
             * @type {string | undefined}
             */
            this["fw_mark"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script before interface up
             * @member
             * @type {string | undefined}
             */
            this["pre_up"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script after interface up
             * @member
             * @type {string | undefined}
             */
            this["post_up"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script before interface down
             * @member
             * @type {string | undefined}
             */
            this["pre_down"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script after interface down
             * @member
             * @type {string | undefined}
             */
            this["post_down"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Unrecognized keys preserved for round-tripping
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["extra_keys"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InterfaceConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("address" in $$parsedSource) {
            $$parsedSource["address"] = $$createField1_0($$parsedSource["address"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField2_0($$parsedSource["dns"]);
        }
        if ("extra_keys" in $$parsedSource) {
            $$parsedSource["extra_keys"] = $$createField11_0($$parsedSource["extra_keys"]);
        }
        return new InterfaceConfig(/** @type {Partial<InterfaceConfig>} */($$parsedSource));
    }
}

/**
 * PeerConfig represents a [Peer] section of a .conf file.
 */
export class PeerConfig {
    /**
     * Creates a new PeerConfig instance.
     * @param {Partial<PeerConfig>} [$$source = {}] - The source object to create the PeerConfig.
     */
    constructor($$source = {}) {
        if (!("public_key" in $$source)) {
            /**
             * Required: Base64-encoded 32-byte key
             * @member
             * @type {string}
             */
            this["public_key"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional
             * @member
             * @type {string | undefined}
             */
            this["preshared_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: host:port
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (!("allowed_ips" in $$source)) {
            /**
             * Required: CIDR list
             * @member
             * @type {string[]}
             */
            this["allowed_ips"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: seconds (0 = disabled)
             * @member
             * @type {number | undefined}
             */
            this["persistent_keepalive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Unrecognized keys preserved for round-tripping
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["extra_keys"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PeerConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowed_ips" in $$parsedSource) {
            $$parsedSource["allowed_ips"] = $$createField3_0($$parsedSource["allowed_ips"]);
        }
        if ("extra_keys" in $$parsedSource) {
            $$parsedSource["extra_keys"] = $$createField5_0($$parsedSource["extra_keys"]);
        }
        return new PeerConfig(/** @type {Partial<PeerConfig>} */($$parsedSource));
    }
}

/**
 * Protocol identifies which VPN backend a tunnel uses. WireGuide+ started as a
 * WireGuard-only client; OpenVPN support was added later. Tunnels created before
 * the protocol field existed have no value in their .meta.json — callers MUST
 * treat the empty string as ProtocolWireGuard for backward compatibility.
 * @readonly
 * @enum {string}
 */
export const Protocol = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ProtocolWireGuard: "wireguard",
    ProtocolOpenVPN: "openvpn",
};

/**
 * State represents the tunnel connection state.
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateDisconnected: "disconnected",
    StateConnecting: "connecting",
    StateConnected: "connected",
    StateError: "error",
};

/**
 * WireGuardConfig represents a complete WireGuard configuration file.
 */
export class WireGuardConfig {
    /**
     * Creates a new WireGuardConfig instance.
     * @param {Partial<WireGuardConfig>} [$$source = {}] - The source object to create the WireGuardConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Tunnel name (derived from filename)
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * [Interface] section
             * @member
             * @type {InterfaceConfig}
             */
            this["interface"] = (new InterfaceConfig());
        }
        if (!("peers" in $$source)) {
            /**
             * [Peer] sections (1 or more)
             * @member
             * @type {PeerConfig[]}
             */
            this["peers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WireGuardConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WireGuardConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interface" in $$parsedSource) {
            $$parsedSource["interface"] = $$createField1_0($$parsedSource["interface"]);
        }
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField2_0($$parsedSource["peers"]);
        }
        return new WireGuardConfig(/** @type {Partial<WireGuardConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ConnectionStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = InterfaceConfig.createFrom;
const $$createType5 = PeerConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
