// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService is the Wails-bound service.
 * Storage (tunnel files, settings) stays in the GUI process.
 * Tunnel operations go through the helper via an ipc.ClientHolder (so the
 * helper can be re-spawned and the connection swapped without rebuilding
 * the whole service graph).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tunnel$0 from "../tunnel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BaseName extracts the filename without extension from a path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function BaseName(path) {
    return $Call.ByID(3469363575, path);
}

/**
 * CheckConflicts loads a tunnel's config and scans local network interfaces
 * for routing overlaps (e.g. Tailscale, another WireGuard instance). Runs
 * entirely in the GUI process — no IPC needed. The frontend calls this before
 * Connect so it can show a warning dialog if conflicts exist.
 * @param {string} name
 * @returns {$CancellablePromise<tunnel$0.ConflictInfo[]>}
 */
export function CheckConflicts(name) {
    return $Call.ByID(3480969502, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckForUpdate queries GitHub for a newer release.
 * @returns {$CancellablePromise<update$0.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(3781738431).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CompleteOnboarding marks onboarding as done in settings.
 * @returns {$CancellablePromise<void>}
 */
export function CompleteOnboarding() {
    return $Call.ByID(4101637083);
}

/**
 * Connect loads a tunnel config from local storage and asks the helper to
 * bring it up. The helper re-validates server-side.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Connect(name) {
    return $Call.ByID(1123040453, name);
}

/**
 * DeleteTunnel removes a tunnel from local storage. Rejects deletion of the
 * currently connected tunnel (would orphan the interface).
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTunnel(name) {
    return $Call.ByID(3822542112, name);
}

/**
 * Disconnect tears down whatever tunnel the helper currently has active.
 * If the call fails with a "client closed" error (the health monitor may have
 * swapped the client during a recovery), retry once with the fresh client.
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(1171530279);
}

/**
 * DisconnectTunnel disconnects a specific tunnel by name.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectTunnel(name) {
    return $Call.ByID(1584259497, name);
}

/**
 * ExportConfig returns the serialized text for display in the export dialog.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig(name) {
    return $Call.ByID(1684823973, name);
}

/**
 * ExportTunnel shows a native save dialog and writes the .conf file.
 * Returns the saved path, or empty string if the user cancelled.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportTunnel(name) {
    return $Call.ByID(686002857, name);
}

/**
 * GetConfigText returns the serialized form of a stored tunnel's config.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigText(name) {
    return $Call.ByID(1065418994, name);
}

/**
 * GetRoutingTable returns the current OS routing table.
 * @returns {$CancellablePromise<$models.RouteEntry[]>}
 */
export function GetRoutingTable() {
    return $Call.ByID(3049102509).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<storage$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2393200110).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetStatus queries the helper for the current connection status. IPC errors
 * are surfaced to the caller — the frontend needs to distinguish "helper says
 * disconnected" from "helper unreachable".
 * @returns {$CancellablePromise<$models.ConnectionStatus | null>}
 */
export function GetStatus() {
    return $Call.ByID(3544552149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetTunnelDetail returns the full WireGuardConfig for a tunnel. Used by the
 * detail pane to show allowed IPs, DNS, public keys, etc.
 * @param {string} name
 * @returns {$CancellablePromise<domain$0.WireGuardConfig | null>}
 */
export function GetTunnelDetail(name) {
    return $Call.ByID(3171898132, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetTunnelMeta returns per-tunnel metadata (auto-reconnect flag etc.).
 * @param {string} name
 * @returns {$CancellablePromise<storage$0.TunnelMeta | null>}
 */
export function GetTunnelMeta(name) {
    return $Call.ByID(4088997336, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetVersion returns the current app version string.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1775430717);
}

/**
 * ImportConfig parses, validates, and saves a tunnel config under the given
 * name. Returns a TunnelInfo for optimistic UI display.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportConfig(name, content) {
    return $Call.ByID(2459134310, name, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ImportFoundConfigs reads and imports the .conf files at the given absolute
 * paths. Returns per-file results reusing the ZipImportResult shape.
 * @param {string[]} paths
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportFoundConfigs(paths) {
    return $Call.ByID(3040882779, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ImportZip extracts all .conf files from a zip archive and imports each one.
 * Returns per-file results; an error is only returned for zip-level failures.
 * @param {string} path
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZip(path) {
    return $Call.ByID(976469479, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ImportZipData imports a zip supplied as raw bytes (used by the file picker,
 * which provides a File object rather than a filesystem path).
 * @param {string} data
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZipData(data) {
    return $Call.ByID(2432663343, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ListTunnels returns every stored tunnel with its summary info.
 * 
 * The active-tunnel marker used to come from an IPC round-trip on every call.
 * That made the tray's rebuild-menu path slow when it was being invoked on
 * the status event stream. The frontend now learns the active tunnel from
 * the status event itself, and the tray caches it internally — so this
 * function stays fully local (disk-only, no IPC) and returns IsConnected
 * purely as a best-effort flag based on a single active-name probe that is
 * safe to skip entirely on slow paths.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnels() {
    return $Call.ByID(3587038916).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ListTunnelsLocal returns stored tunnels WITHOUT asking the helper which one
 * is active — callers that already know the active name (e.g. the system
 * tray, which tracks it from the status event stream) should use this to
 * avoid an IPC round-trip on every refresh. IsConnected is always false in
 * the returned slice; the caller is responsible for applying its own
 * active-name match.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnelsLocal() {
    return $Call.ByID(3031176175).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * OpenURL opens a URL in the default browser. Only HTTPS URLs on
 * github.com are allowed to prevent misuse from a compromised frontend.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(1649174774, url);
}

/**
 * ReadFile reads a file from disk (used by native file drop). Returns the
 * content as a string so the frontend can handle name conflicts before import.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1950850135, path);
}

/**
 * RenameTunnel changes a tunnel's name. Rejects rename of the connected
 * tunnel since the interface name is derived from it.
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTunnel(oldName, newName) {
    return $Call.ByID(576069505, oldName, newName);
}

/**
 * RunDNSLeakTest performs a DNS leak test using the currently active tunnel's
 * DNS servers as the expected (VPN) resolvers. If no tunnel is connected, the
 * expected set is empty — all detected resolvers will be flagged as leaks.
 * @returns {$CancellablePromise<$models.DNSLeakResult | null>}
 */
export function RunDNSLeakTest() {
    return $Call.ByID(2469114850).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * RunUpdate performs the update. If installed via Homebrew, runs brew upgrade.
 * Otherwise downloads and installs directly from GitHub Releases.
 * @param {update$0.UpdateInfo | null} info
 * @returns {$CancellablePromise<void>}
 */
export function RunUpdate(info) {
    return $Call.ByID(2959589127, info);
}

/**
 * SaveSettings persists the settings file AND applies any side effects:
 * currently, pushing the new log level to both the GUI's slog handler and
 * the helper's slog handler. Without those side effects a user lowering the
 * level to Debug wouldn't see any new records — the saved file would match
 * the UI but the running process would still be at Info.
 * @param {storage$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3676285513, settings);
}

/**
 * SaveTunnelMeta persists per-tunnel metadata.
 * @param {string} name
 * @param {storage$0.TunnelMeta} meta
 * @returns {$CancellablePromise<void>}
 */
export function SaveTunnelMeta(name, meta) {
    return $Call.ByID(185268851, name, meta);
}

/**
 * ScanForWireGuardConfigs returns existing WireGuard configs found on the
 * filesystem that haven't been imported into WireGuide+ yet.
 * @returns {$CancellablePromise<$models.FoundConfig[]>}
 */
export function ScanForWireGuardConfigs() {
    return $Call.ByID(1549830634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * SetApp injects the Wails app for dialog access.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1760917394, app);
}

/**
 * SetDNSProtection asks the helper to lock DNS to the active tunnel's servers.
 * When enabling, we look up the active tunnel's DNS list from local storage
 * and pass it along (the helper never touches user-space storage).
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDNSProtection(enabled) {
    return $Call.ByID(472068929, enabled);
}

/**
 * SetHealthCheck enables or disables the tunnel health check monitor.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetHealthCheck(enabled) {
    return $Call.ByID(1079240195, enabled);
}

/**
 * SetKillSwitch asks the helper to enable or disable the firewall kill switch.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetKillSwitch(enabled) {
    return $Call.ByID(1469047591, enabled);
}

/**
 * SetLogLevel updates both the GUI's and the helper's slog level
 * immediately. Exposed as a Wails method so the Settings view can call
 * it without waiting for a full SaveSettings round trip.
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(537242663, level);
}

/**
 * SetPinInterface enables or disables -ifscope bypass route pinning.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPinInterface(enabled) {
    return $Call.ByID(1245113173, enabled);
}

/**
 * TunnelExists reports whether a tunnel with the given name is stored.
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function TunnelExists(name) {
    return $Call.ByID(1252108931, name);
}

/**
 * UpdateConfig parses, validates, and overwrites an existing tunnel's config.
 * Rejects edits of the connected tunnel.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(name, content) {
    return $Call.ByID(660046974, name, content);
}

/**
 * ValidateConfig parses and validates a raw config string. Returns a list of
 * human-readable error messages, or nil if the config is valid.
 * @param {string} content
 * @returns {$CancellablePromise<string[]>}
 */
export function ValidateConfig(content) {
    return $Call.ByID(592398029, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

// Private type creation functions
const $$createType0 = tunnel$0.ConflictInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = update$0.UpdateInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.RouteEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = storage$0.Settings.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = domain$0.ConnectionStatus.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = domain$0.WireGuardConfig.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = storage$0.TunnelMeta.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.TunnelInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.ZipImportResult.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($$createType14);
const $$createType19 = $models.DNSLeakResult.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $models.FoundConfig.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($Create.Any);
