// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HelperEvent notifies the frontend about helper process health changes.
 */
export class HelperEvent {
    /**
     * Creates a new HelperEvent instance.
     * @param {Partial<HelperEvent>} [$$source = {}] - The source object to create the HelperEvent.
     */
    constructor($$source = {}) {
        if (!("alive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alive"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelperEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HelperEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelperEvent(/** @type {Partial<HelperEvent>} */($$parsedSource));
    }
}

/**
 * ReconnectEvent mirrors ipc.ReconnectStateDTO for Wails event emission.
 */
export class ReconnectEvent {
    /**
     * Creates a new ReconnectEvent instance.
     * @param {Partial<ReconnectEvent>} [$$source = {}] - The source object to create the ReconnectEvent.
     */
    constructor($$source = {}) {
        if (!("reconnecting" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reconnecting"] = false;
        }
        if (!("attempt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempt"] = 0;
        }
        if (!("max_attempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_attempts"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconnectEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReconnectEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconnectEvent(/** @type {Partial<ReconnectEvent>} */($$parsedSource));
    }
}
